### ISSUE TITLE
Activity: Add an image to your profile

### ISSUE THREAD

**Issue by hectorsector** [github-scholars/atlanta#64]
To add an image to your profile, add `image: ` and a link to your profile inside the `_scholars` folder, like this:

```yml
---
layout: generic
title: Hector Alfaro
description: Trainer for GitHub
image: https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/7/005/08c/24f/38c031d.jpg
---

Resume: https://githubteacher.github.io/resume/
```

See how it's done [here](https://github.com/github-scholars/atlanta/blame/4ec62172b7db1ab1e38b1d7d0254669e5cf6ed66/_scholars/hector.md#L5).
